# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:24
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', inventory.models.UpperCaseCharField(default='', max_length=40, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', inventory.models.UpperCaseCharField(default='', max_length=40)),
                ('category', models.ManyToManyField(to='inventory.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', inventory.models.UpperCaseCharField(default='', max_length=40, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', inventory.models.UpperCaseCharField(default='', max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemlocation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Section'),
        ),
        migrations.AddField(
            model_name='itemlocation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer'),
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.ManyToManyField(through='inventory.ItemLocation', to='inventory.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('name', 'manufacturer')]),
        ),
    ]
