# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:24
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default='???', max_length=30)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('vac_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vacation days to use:')),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
