# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 11:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20170823_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vac_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
