# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_vacation_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='user',
            field=models.CharField(default='???', max_length=30),
        ),
    ]
