# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_vacation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vac_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vacation days to use:'),
        ),
    ]
